/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventLocalAddressChanged */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventLocalAddressChanged
#define _Included_io_vproxy_msquic_QuicConnectionEventLocalAddressChanged
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventLocalAddressChanged;
typedef struct QuicConnectionEventLocalAddressChanged QuicConnectionEventLocalAddressChanged;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicAddr.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventLocalAddressChanged, QuicConnectionEventLocalAddressChanged *)
PNIBufExpand(QuicConnectionEventLocalAddressChanged, QuicConnectionEventLocalAddressChanged, 8)

struct QuicConnectionEventLocalAddressChanged {
    QUIC_ADDR * Address;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventLocalAddressChanged
// metadata.generator-version: pni 21.0.0.16
// sha256:009ec1ee2d4892ce21eed0b41b4d3f236ee3202a3a34850718678aff380068a6
