/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicApiTable */
#ifndef _Included_io_vproxy_msquic_QuicApiTable
#define _Included_io_vproxy_msquic_QuicApiTable
#ifdef __cplusplus
extern "C" {
#endif

struct QuicApiTable;
typedef struct QuicApiTable QuicApiTable;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicRegistration.h"
#include "io_vproxy_msquic_QuicRegistrationConfig.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicApiTable, QuicApiTable *)
PNIBufExpand(QuicApiTable, QuicApiTable, 8)

struct QuicApiTable {
    void * Api;
};

JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicApiTable_close(QuicApiTable * self);
JNIEXPORT QuicRegistration * JNICALL JavaCritical_io_vproxy_msquic_QuicApiTable_openRegistration(QuicApiTable * self, QUIC_REGISTRATION_CONFIG * Config, int32_t * returnStatus, QuicRegistration * return_);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicApiTable
// metadata.generator-version: pni 21.0.0.17
// sha256:908c02c135b7f09f95eb650d00e7f712b93f08ddb341f55a678c435d2e2ae47d
