/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicCertificate */
#ifndef _Included_io_vproxy_msquic_QuicCertificate
#define _Included_io_vproxy_msquic_QuicCertificate
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicCertificateFile.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicCertificate
// metadata.generator-version: pni 21.0.0.16
// sha256:05c3d5c754191d27f1b5b3f17aa52264f301e0f12ae06a654b4758a267753fad
