/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_MsQuicModUpcall */
#ifndef _Included_io_vproxy_msquic_MsQuicModUpcall
#define _Included_io_vproxy_msquic_MsQuicModUpcall
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_CXPLAT_THREAD_CONFIG.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicModUpcall_dispatch(CXPLAT_THREAD_CONFIG * Config, CXPLAT_EVENTQ * EventQ, void * Thread, void * Context);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_MsQuicModUpcall
// metadata.generator-version: pni 21.0.0.16
// sha256:62b74c2c78fae3d4c61e9b3f602d316e888e7be4253f7d5a7aa8d2f1de9c91f7
