/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_MsQuicMod */
#ifndef _Included_io_vproxy_msquic_MsQuicMod
#define _Included_io_vproxy_msquic_MsQuicMod
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL MsQuicSetThreadCountLimit(uint32_t limit);
JNIEXPORT QUIC_STATUS JNICALL MsQuicSetEventLoopThreadDispatcher(QUIC_EVENT_LOOP_THREAD_DISPATCH_FN dispatcher);
JNIEXPORT QUIC_STATUS JNICALL CxPlatGetCurThread(CXPLAT_THREAD* Thread);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_MsQuicMod_INVOKE_LPTHREAD_START_ROUTINE(void * Callback, void * Context);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_MsQuicMod
// metadata.generator-version: pni 21.0.0.17
// sha256:cb62af6d9a6eec9cd34956b68e4809cbee250c432dbe555a6917182436314a4f
