/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicListenerEventNewConnection */
#ifndef _Included_io_vproxy_msquic_QuicListenerEventNewConnection
#define _Included_io_vproxy_msquic_QuicListenerEventNewConnection
#ifdef __cplusplus
extern "C" {
#endif

struct QuicListenerEventNewConnection;
typedef struct QuicListenerEventNewConnection QuicListenerEventNewConnection;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicNewConnectionInfo.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicListenerEventNewConnection, QuicListenerEventNewConnection *)
PNIBufExpand(QuicListenerEventNewConnection, QuicListenerEventNewConnection, 16)

struct QuicListenerEventNewConnection {
    QUIC_NEW_CONNECTION_INFO * Info;
    void * Connection;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicListenerEventNewConnection
// metadata.generator-version: pni 21.0.0.16
// sha256:913f6e9659008b700985a0f929862ecbf187ded9e2285d67b4c9a5be8c1a78cd
