/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventPeerNeedsStreams */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventPeerNeedsStreams
#define _Included_io_vproxy_msquic_QuicConnectionEventPeerNeedsStreams
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventPeerNeedsStreams;
typedef struct QuicConnectionEventPeerNeedsStreams QuicConnectionEventPeerNeedsStreams;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventPeerNeedsStreams, QuicConnectionEventPeerNeedsStreams *)
PNIBufExpand(QuicConnectionEventPeerNeedsStreams, QuicConnectionEventPeerNeedsStreams, 1)

struct QuicConnectionEventPeerNeedsStreams {
    uint8_t Bidirectional;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventPeerNeedsStreams
// metadata.generator-version: pni 21.0.0.16
// sha256:35b1ac0fce307eccbcf24192042d083f66d54e3aae157a51d6fa2de1a1d2e0cd
