/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicListenerEventStopComplete */
#ifndef _Included_io_vproxy_msquic_QuicListenerEventStopComplete
#define _Included_io_vproxy_msquic_QuicListenerEventStopComplete
#ifdef __cplusplus
extern "C" {
#endif

struct QuicListenerEventStopComplete;
typedef struct QuicListenerEventStopComplete QuicListenerEventStopComplete;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicListenerEventStopComplete, QuicListenerEventStopComplete *)
PNIBufExpand(QuicListenerEventStopComplete, QuicListenerEventStopComplete, 1)

struct QuicListenerEventStopComplete {
    uint8_t AppCloseInProgress : 1;
    uint8_t : 7;

};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicListenerEventStopComplete
// metadata.generator-version: pni 21.0.0.16
// sha256:8d5536fe145fbcf4b953575672a3b0523d479b22a59a76c267fd26abd6240aca
