/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicListener */
#ifndef _Included_io_vproxy_msquic_QuicListener
#define _Included_io_vproxy_msquic_QuicListener
#ifdef __cplusplus
extern "C" {
#endif

struct QuicListener;
typedef struct QuicListener QuicListener;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicBuffer.h"
#include "io_vproxy_msquic_QuicAddr.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicListener, QuicListener *)
PNIBufExpand(QuicListener, QuicListener, 16)

struct QuicListener {
    void * Api;
    void * Lsn;
};

JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicListener_close(QuicListener * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicListener_start(QuicListener * self, QUIC_BUFFER * AlpnBuffers, int32_t AlpnBufferCount, QUIC_ADDR * Addr);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicListener_stop(QuicListener * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicListener
// metadata.generator-version: pni 21.0.0.16
// sha256:a6421de0c2214d38d04b12300c9dc36d661abf48635fdb0d728047a205ec6c0d
