/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicCertificateFile */
#ifndef _Included_io_vproxy_msquic_QuicCertificateFile
#define _Included_io_vproxy_msquic_QuicCertificateFile
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_CERTIFICATE_FILE, QUIC_CERTIFICATE_FILE *)
PNIBufExpand(QUIC_CERTIFICATE_FILE, QUIC_CERTIFICATE_FILE, 16)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicCertificateFile
// metadata.generator-version: pni 21.0.0.16
// sha256:998d4920d1a9dca147693174416ea167a3ad73b82eafed66b08d78b11254bff8
