/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventDatagramSendStateChanged */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventDatagramSendStateChanged
#define _Included_io_vproxy_msquic_QuicConnectionEventDatagramSendStateChanged
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventDatagramSendStateChanged;
typedef struct QuicConnectionEventDatagramSendStateChanged QuicConnectionEventDatagramSendStateChanged;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventDatagramSendStateChanged, QuicConnectionEventDatagramSendStateChanged *)
PNIBufExpand(QuicConnectionEventDatagramSendStateChanged, QuicConnectionEventDatagramSendStateChanged, 16)

struct QuicConnectionEventDatagramSendStateChanged {
    void * ClientContext;
    int32_t State;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventDatagramSendStateChanged
// metadata.generator-version: pni 21.0.0.16
// sha256:df95a2329e6acdeeaaee205e54cd018f33ec488219fed60cc5bccefb0d70e947
