/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicListenerEventUnion */
#ifndef _Included_io_vproxy_msquic_QuicListenerEventUnion
#define _Included_io_vproxy_msquic_QuicListenerEventUnion
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicListenerEventNewConnection.h"
#include "io_vproxy_msquic_QuicListenerEventStopComplete.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicListenerEventUnion
// metadata.generator-version: pni 21.0.0.16
// sha256:1fc207526208ba3130ed1f76e2125d982ebda35e249984a97624369c28637a98
