/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventPeerCertificateReceived */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventPeerCertificateReceived
#define _Included_io_vproxy_msquic_QuicConnectionEventPeerCertificateReceived
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventPeerCertificateReceived;
typedef struct QuicConnectionEventPeerCertificateReceived QuicConnectionEventPeerCertificateReceived;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventPeerCertificateReceived, QuicConnectionEventPeerCertificateReceived *)
PNIBufExpand(QuicConnectionEventPeerCertificateReceived, QuicConnectionEventPeerCertificateReceived, 24)

struct QuicConnectionEventPeerCertificateReceived {
    void * Certificate;
    uint32_t DeferredErrorFlags;
    int32_t DeferredStatus;
    void * Chain;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventPeerCertificateReceived
// metadata.generator-version: pni 21.0.0.16
// sha256:de4be49e89e23fd57db6d02f3be66a4a8bdfe36b80f6cfc718501b1f7a8f5cde
