/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventResumptionTicketReceived */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventResumptionTicketReceived
#define _Included_io_vproxy_msquic_QuicConnectionEventResumptionTicketReceived
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventResumptionTicketReceived;
typedef struct QuicConnectionEventResumptionTicketReceived QuicConnectionEventResumptionTicketReceived;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventResumptionTicketReceived, QuicConnectionEventResumptionTicketReceived *)
PNIBufExpand(QuicConnectionEventResumptionTicketReceived, QuicConnectionEventResumptionTicketReceived, 16)

struct QuicConnectionEventResumptionTicketReceived {
    uint32_t ResumptionTicketLength;
    void * ResumptionTicket;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventResumptionTicketReceived
// metadata.generator-version: pni 21.0.0.16
// sha256:07c1c6eff3b9b163d144cc28be435f0ce75ebda8c0548a67d52e11bb9dc74561
