/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventPeerSendAborted */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventPeerSendAborted
#define _Included_io_vproxy_msquic_QuicStreamEventPeerSendAborted
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventPeerSendAborted;
typedef struct QuicStreamEventPeerSendAborted QuicStreamEventPeerSendAborted;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventPeerSendAborted, QuicStreamEventPeerSendAborted *)
PNIBufExpand(QuicStreamEventPeerSendAborted, QuicStreamEventPeerSendAborted, 8)

struct QuicStreamEventPeerSendAborted {
    int64_t ErrorCode;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventPeerSendAborted
// metadata.generator-version: pni 21.0.0.16
// sha256:491e5b15632a030ab5e7a008fe78a10cf7133f2ec27f7a0c953acefdb4fbd5e4
