/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_MsQuicUpcall */
#ifndef _Included_io_vproxy_msquic_MsQuicUpcall
#define _Included_io_vproxy_msquic_MsQuicUpcall
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicListenerEvent.h"
#include "io_vproxy_msquic_QuicConnectionEvent.h"
#include "io_vproxy_msquic_QuicStreamEvent.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicUpcall_listenerCallback(void * Listener, void * Context, QUIC_LISTENER_EVENT * Event);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicUpcall_connectionCallback(void * Connection, void * Context, QUIC_CONNECTION_EVENT * Event);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicUpcall_streamCallback(void * Stream, void * Context, QUIC_STREAM_EVENT * Event);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_MsQuicUpcall
// metadata.generator-version: pni 21.0.0.16
// sha256:38d59aaa0652ea4be2fe6b1c4d114b4f534fded668b03d52e9ed8b99c54e8a9d
