/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicCredentialConfig */
#ifndef _Included_io_vproxy_msquic_QuicCredentialConfig
#define _Included_io_vproxy_msquic_QuicCredentialConfig
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicCertificate.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_CREDENTIAL_CONFIG, QUIC_CREDENTIAL_CONFIG *)
PNIBufExpand(QUIC_CREDENTIAL_CONFIG, QUIC_CREDENTIAL_CONFIG, 56)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicCredentialConfig
// metadata.generator-version: pni 21.0.0.16
// sha256:b4c78ff7e7054fc120645204841be1bb26eb53c93b787564af8d51969e822313
