/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_CXPLAT_THREAD_CONFIG */
#ifndef _Included_io_vproxy_msquic_CXPLAT_THREAD_CONFIG
#define _Included_io_vproxy_msquic_CXPLAT_THREAD_CONFIG
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(CXPLAT_THREAD_CONFIG, CXPLAT_THREAD_CONFIG *)
PNIBufExpand(CXPLAT_THREAD_CONFIG, CXPLAT_THREAD_CONFIG, 32)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_CXPLAT_THREAD_CONFIG
// metadata.generator-version: pni 21.0.0.16
// sha256:328978cb80cf1041e3fad8948a256c53d1d99a6232e0b809495c82028d5fbbed
