/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventIdealProcessorChanged */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventIdealProcessorChanged
#define _Included_io_vproxy_msquic_QuicConnectionEventIdealProcessorChanged
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventIdealProcessorChanged;
typedef struct QuicConnectionEventIdealProcessorChanged QuicConnectionEventIdealProcessorChanged;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventIdealProcessorChanged, QuicConnectionEventIdealProcessorChanged *)
PNIBufExpand(QuicConnectionEventIdealProcessorChanged, QuicConnectionEventIdealProcessorChanged, 4)

struct QuicConnectionEventIdealProcessorChanged {
    uint16_t IdealProcessor;
    uint16_t PartitionIndex;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventIdealProcessorChanged
// metadata.generator-version: pni 21.0.0.16
// sha256:074ba5d8b8f9c3fcaace868bc6e7108ec03b46ff6e4a9cb67849bb3dce104435
