/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventPeerReceiveAborted */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventPeerReceiveAborted
#define _Included_io_vproxy_msquic_QuicStreamEventPeerReceiveAborted
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventPeerReceiveAborted;
typedef struct QuicStreamEventPeerReceiveAborted QuicStreamEventPeerReceiveAborted;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventPeerReceiveAborted, QuicStreamEventPeerReceiveAborted *)
PNIBufExpand(QuicStreamEventPeerReceiveAborted, QuicStreamEventPeerReceiveAborted, 8)

struct QuicStreamEventPeerReceiveAborted {
    int64_t ErrorCode;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventPeerReceiveAborted
// metadata.generator-version: pni 21.0.0.16
// sha256:499eb8fd2056d413733f39acb2e14e629267b860c144245eee988edd2f376944
