/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicBuffer */
#ifndef _Included_io_vproxy_msquic_QuicBuffer
#define _Included_io_vproxy_msquic_QuicBuffer
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_BUFFER, QUIC_BUFFER *)
PNIBufExpand(QUIC_BUFFER, QUIC_BUFFER, 16)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicBuffer
// metadata.generator-version: pni 21.0.0.16
// sha256:d671b66f1d0b3e09f7c0b9f39d42c9305d1d5db5c25791ee006b775cca4da76e
