/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicRegistrationConfig */
#ifndef _Included_io_vproxy_msquic_QuicRegistrationConfig
#define _Included_io_vproxy_msquic_QuicRegistrationConfig
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_REGISTRATION_CONFIG, QUIC_REGISTRATION_CONFIG *)
PNIBufExpand(QUIC_REGISTRATION_CONFIG, QUIC_REGISTRATION_CONFIG, 16)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicRegistrationConfig
// metadata.generator-version: pni 21.0.0.16
// sha256:4e3f5d3aae49a8f3ffdc7599e653e67e16d89f0f9a01aaea07ed638346ee60e3
