/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicAddr */
#ifndef _Included_io_vproxy_msquic_QuicAddr
#define _Included_io_vproxy_msquic_QuicAddr
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_msquic_QuicAddr___getLayoutByteSize();

PNIEnvExpand(QUIC_ADDR, QUIC_ADDR *)
PNIBufExpand(QUIC_ADDR, QUIC_ADDR, JavaCritical_io_vproxy_msquic_QuicAddr___getLayoutByteSize())

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_getFamily(QUIC_ADDR * self);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_setFamily(QUIC_ADDR * self, int32_t family);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_getPort(QUIC_ADDR * self);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_setPort(QUIC_ADDR * self, int32_t port);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_toString(QUIC_ADDR * self, char * str);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicAddr
// metadata.generator-version: pni 21.0.0.16
// sha256:783b22f6cd7c46485cf8e8b49ffa44ef72ab60c31a3a3342b35f0045e0c85f36
