/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventSendComplete */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventSendComplete
#define _Included_io_vproxy_msquic_QuicStreamEventSendComplete
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventSendComplete;
typedef struct QuicStreamEventSendComplete QuicStreamEventSendComplete;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventSendComplete, QuicStreamEventSendComplete *)
PNIBufExpand(QuicStreamEventSendComplete, QuicStreamEventSendComplete, 16)

struct QuicStreamEventSendComplete {
    uint8_t Canceled;
    void * ClientContext;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventSendComplete
// metadata.generator-version: pni 21.0.0.16
// sha256:61045224647e55f8be3a84512d8392db65912166fb584b183a9de66a50460e89
