/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicListener */
#ifndef _Included_io_vproxy_msquic_QuicListener
#define _Included_io_vproxy_msquic_QuicListener
#ifdef __cplusplus
extern "C" {
#endif

struct QuicListener;
typedef struct QuicListener QuicListener;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicObjectBase.h"
#include "io_vproxy_msquic_QuicBuffer.h"
#include "io_vproxy_msquic_QuicAddr.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicListener, QuicListener *)
PNIBufExpand(QuicListener, QuicListener, 16)

struct QuicListener {
    QuicObjectBase SUPER;
};

JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicListener_close(QuicListener * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicListener_start(QuicListener * self, QUIC_BUFFER * AlpnBuffers, int32_t AlpnBufferCount, QUIC_ADDR * Addr);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicListener_stop(QuicListener * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicListener
// metadata.generator-version: pni 21.0.0.17
// sha256:bb27eaac2026863e730e8c013663340cc0891d641144ee05427af26655c381f8
