/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventPeerAddressChanged */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventPeerAddressChanged
#define _Included_io_vproxy_msquic_QuicConnectionEventPeerAddressChanged
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventPeerAddressChanged;
typedef struct QuicConnectionEventPeerAddressChanged QuicConnectionEventPeerAddressChanged;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicAddr.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventPeerAddressChanged, QuicConnectionEventPeerAddressChanged *)
PNIBufExpand(QuicConnectionEventPeerAddressChanged, QuicConnectionEventPeerAddressChanged, 8)

struct QuicConnectionEventPeerAddressChanged {
    QUIC_ADDR * Address;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventPeerAddressChanged
// metadata.generator-version: pni 21.0.0.16
// sha256:fda8d8f455228477d146ce7c69a284f9b27840b3028c7748da29f15e1cd12f0b
