/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConfiguration */
#ifndef _Included_io_vproxy_msquic_QuicConfiguration
#define _Included_io_vproxy_msquic_QuicConfiguration
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConfiguration;
typedef struct QuicConfiguration QuicConfiguration;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicCredentialConfig.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConfiguration, QuicConfiguration *)
PNIBufExpand(QuicConfiguration, QuicConfiguration, 16)

struct QuicConfiguration {
    void * Api;
    void * Conf;
};

JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicConfiguration_close(QuicConfiguration * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicConfiguration_loadCredential(QuicConfiguration * self, QUIC_CREDENTIAL_CONFIG * CredConfig);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConfiguration
// metadata.generator-version: pni 21.0.0.16
// sha256:3ca9e3152a54f385d357aa7304087ff1acdc6397c849e048543f5b9f43d59f06
