/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEvent */
#ifndef _Included_io_vproxy_msquic_QuicStreamEvent
#define _Included_io_vproxy_msquic_QuicStreamEvent
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicStreamEventUnion.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_STREAM_EVENT, QUIC_STREAM_EVENT *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEvent
// metadata.generator-version: pni 21.0.0.8
// sha256:fe70c389f8dcba32f839c530401118ffc0b8146750591723fe98f84cf1120b79
