/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventResumed */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventResumed
#define _Included_io_vproxy_msquic_QuicConnectionEventResumed
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventResumed;
typedef struct QuicConnectionEventResumed QuicConnectionEventResumed;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventResumed, QuicConnectionEventResumed *)
PNIBufExpand(QuicConnectionEventResumed, QuicConnectionEventResumed, 16)

struct QuicConnectionEventResumed {
    uint16_t ResumptionStateLength;
    void * ResumptionState;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventResumed
// metadata.generator-version: pni 21.0.0.13
// sha256:46ef71c48d53a0adb715a851e796d8d47f5287220950012c75370cadc3f2867c
