/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventShutdownComplete */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventShutdownComplete
#define _Included_io_vproxy_msquic_QuicStreamEventShutdownComplete
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventShutdownComplete;
typedef struct QuicStreamEventShutdownComplete QuicStreamEventShutdownComplete;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventShutdownComplete, QuicStreamEventShutdownComplete *)

PNI_PACK(struct, QuicStreamEventShutdownComplete, {
    uint8_t ConnectionShutdown;
    uint8_t AppCloseInProgress : 1;
    uint8_t ConnectionShutdownByApp : 1;
    uint8_t ConnectionClosedRemotely : 1;
    uint8_t : 5;
     /* padding */ uint64_t :48;
    int64_t ConnectionErrorCode;
    int32_t ConnectionCloseStatus; /* padding */ uint64_t :32;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventShutdownComplete
// metadata.generator-version: pni 21.0.0.8
// sha256:5ac943cca945e3f0fb010acb008eb246c5bdedf6c6e982858c32cc2ee863944e
