/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicListenerEventStopComplete */
#ifndef _Included_io_vproxy_msquic_QuicListenerEventStopComplete
#define _Included_io_vproxy_msquic_QuicListenerEventStopComplete
#ifdef __cplusplus
extern "C" {
#endif

struct QuicListenerEventStopComplete;
typedef struct QuicListenerEventStopComplete QuicListenerEventStopComplete;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicListenerEventStopComplete, QuicListenerEventStopComplete *)

PNI_PACK(struct, QuicListenerEventStopComplete, {
    uint8_t AppCloseInProgress : 1;
    uint8_t : 7;

});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicListenerEventStopComplete
// metadata.generator-version: pni 21.0.0.8
// sha256:6cfe28293f30678d23b067903b76eeb9420e8a04ec8b7e4477f5f62c935801c5
