/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicListener */
#ifndef _Included_io_vproxy_msquic_QuicListener
#define _Included_io_vproxy_msquic_QuicListener
#ifdef __cplusplus
extern "C" {
#endif

struct QuicListener;
typedef struct QuicListener QuicListener;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicBuffer.h"
#include "io_vproxy_msquic_QuicAddr.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicListener, QuicListener *)

PNI_PACK(struct, QuicListener, {
    void * Api;
    void * Lsn;
});

JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicListener_close(QuicListener * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicListener_start(QuicListener * self, QUIC_BUFFER * AlpnBuffers, int32_t AlpnBufferCount, QUIC_ADDR * Addr);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicListener_stop(QuicListener * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicListener
// metadata.generator-version: pni 21.0.0.8
// sha256:c8e015964b0ddb2e879cdc66ddd6f8699a9138542fc65cad365edc759d6b9ca1
