/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicTLSSecretIsSet */
#ifndef _Included_io_vproxy_msquic_QuicTLSSecretIsSet
#define _Included_io_vproxy_msquic_QuicTLSSecretIsSet
#ifdef __cplusplus
extern "C" {
#endif

struct QuicTLSSecretIsSet;
typedef struct QuicTLSSecretIsSet QuicTLSSecretIsSet;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicTLSSecretIsSet, QuicTLSSecretIsSet *)
PNIBufExpand(QuicTLSSecretIsSet, QuicTLSSecretIsSet, 1)

struct QuicTLSSecretIsSet {
    uint8_t ClientRandom : 1;
    uint8_t ClientEarlyTrafficSecret : 1;
    uint8_t ClientHandshakeTrafficSecret : 1;
    uint8_t ServerHandshakeTrafficSecret : 1;
    uint8_t ClientTrafficSecret0 : 1;
    uint8_t ServerTrafficSecret0 : 1;
    uint8_t : 2;

};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicTLSSecretIsSet
// metadata.generator-version: pni 21.0.0.13
// sha256:f3a594e1f75523e2d93b8a53a72a4878d9bec4cbb8a1757aad53029a52c20176
