/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicRegistrationConfigEx */
#ifndef _Included_io_vproxy_msquic_QuicRegistrationConfigEx
#define _Included_io_vproxy_msquic_QuicRegistrationConfigEx
#ifdef __cplusplus
extern "C" {
#endif

struct QuicRegistrationConfigEx;
typedef struct QuicRegistrationConfigEx QuicRegistrationConfigEx;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_msquic_QuicRegistrationConfig.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicRegistrationConfigEx, QuicRegistrationConfigEx *)
PNIBufExpand(QuicRegistrationConfigEx, QuicRegistrationConfigEx, 24)

struct QuicRegistrationConfigEx {
    QUIC_REGISTRATION_CONFIG SUPER;
    void * Context;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicRegistrationConfigEx
// metadata.generator-version: pni 21.0.0.16
// sha256:914fab991cbf92b3f93b14c42a6f75502d2b53eb5530b21eb49a9daa1e6401b2
