/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventDatagramStateChanged */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventDatagramStateChanged
#define _Included_io_vproxy_msquic_QuicConnectionEventDatagramStateChanged
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventDatagramStateChanged;
typedef struct QuicConnectionEventDatagramStateChanged QuicConnectionEventDatagramStateChanged;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventDatagramStateChanged, QuicConnectionEventDatagramStateChanged *)
PNIBufExpand(QuicConnectionEventDatagramStateChanged, QuicConnectionEventDatagramStateChanged, 4)

struct QuicConnectionEventDatagramStateChanged {
    uint8_t SendEnabled;
    uint16_t MaxSendLength;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventDatagramStateChanged
// metadata.generator-version: pni 21.0.0.13
// sha256:1d05fb066f27f2b7a898dd7cd1b92c622319569208b8059a8b926c72ff4ddbbd
