/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventPeerStreamStarted */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventPeerStreamStarted
#define _Included_io_vproxy_msquic_QuicConnectionEventPeerStreamStarted
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventPeerStreamStarted;
typedef struct QuicConnectionEventPeerStreamStarted QuicConnectionEventPeerStreamStarted;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventPeerStreamStarted, QuicConnectionEventPeerStreamStarted *)

PNI_PACK(struct, QuicConnectionEventPeerStreamStarted, {
    void * Stream;
    int32_t Flags; /* padding */ uint64_t :32;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventPeerStreamStarted
// metadata.generator-version: pni 21.0.0.8
// sha256:0fbc52aa6df41075b6994f34f4b161b6f96b58781aa52e8f023994e1714311e4
