/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventPeerNeedsStreams */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventPeerNeedsStreams
#define _Included_io_vproxy_msquic_QuicConnectionEventPeerNeedsStreams
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventPeerNeedsStreams;
typedef struct QuicConnectionEventPeerNeedsStreams QuicConnectionEventPeerNeedsStreams;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventPeerNeedsStreams, QuicConnectionEventPeerNeedsStreams *)

PNI_PACK(struct, QuicConnectionEventPeerNeedsStreams, {
    uint8_t Bidirectional;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventPeerNeedsStreams
// metadata.generator-version: pni 21.0.0.8
// sha256:7e08975a4b09cec0bc14235a35876a0792e246377c4a7ceb5cf53e26efd69cec
