/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventPeerCertificateReceived */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventPeerCertificateReceived
#define _Included_io_vproxy_msquic_QuicConnectionEventPeerCertificateReceived
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventPeerCertificateReceived;
typedef struct QuicConnectionEventPeerCertificateReceived QuicConnectionEventPeerCertificateReceived;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventPeerCertificateReceived, QuicConnectionEventPeerCertificateReceived *)

PNI_PACK(struct, QuicConnectionEventPeerCertificateReceived, {
    void * Certificate;
    uint32_t DeferredErrorFlags;
    int32_t DeferredStatus;
    void * Chain;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventPeerCertificateReceived
// metadata.generator-version: pni 21.0.0.8
// sha256:d48a5ed43d86b0d10817f319e1155efa395db80c0279d6d82657a7cda19e5486
