/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicListenerEventNewConnection */
#ifndef _Included_io_vproxy_msquic_QuicListenerEventNewConnection
#define _Included_io_vproxy_msquic_QuicListenerEventNewConnection
#ifdef __cplusplus
extern "C" {
#endif

struct QuicListenerEventNewConnection;
typedef struct QuicListenerEventNewConnection QuicListenerEventNewConnection;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicNewConnectionInfo.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicListenerEventNewConnection, QuicListenerEventNewConnection *)

PNI_PACK(struct, QuicListenerEventNewConnection, {
    QUIC_NEW_CONNECTION_INFO * Info;
    void * Connection;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicListenerEventNewConnection
// metadata.generator-version: pni 21.0.0.8
// sha256:6b93cd892d657506b37778b482610d9fcc0a3da5b7cb63cf1d25193dd8332ed6
