/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventConnected */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventConnected
#define _Included_io_vproxy_msquic_QuicConnectionEventConnected
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventConnected;
typedef struct QuicConnectionEventConnected QuicConnectionEventConnected;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventConnected, QuicConnectionEventConnected *)

PNI_PACK(struct, QuicConnectionEventConnected, {
    uint8_t SessionResumed;
    uint8_t NegotiatedAlpnLength; /* padding */ uint64_t :48;
    void * NegotiatedAlpn;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventConnected
// metadata.generator-version: pni 21.0.0.8
// sha256:7760d4268817e638e78db9945d9035c55efb1ed929a24ceff67310d7ad206ca7
