/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventStreamsAvailable */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventStreamsAvailable
#define _Included_io_vproxy_msquic_QuicConnectionEventStreamsAvailable
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventStreamsAvailable;
typedef struct QuicConnectionEventStreamsAvailable QuicConnectionEventStreamsAvailable;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventStreamsAvailable, QuicConnectionEventStreamsAvailable *)
PNIBufExpand(QuicConnectionEventStreamsAvailable, QuicConnectionEventStreamsAvailable, 4)

struct QuicConnectionEventStreamsAvailable {
    uint16_t BidirectionalCount;
    uint16_t UnidirectionalCount;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventStreamsAvailable
// metadata.generator-version: pni 21.0.0.13
// sha256:20d15081b843a61f247e6c4bad7580e07ca468bdc6cc2e9e3ac0a5c4404f0073
