/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventShutdownInitiatedByPeer */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventShutdownInitiatedByPeer
#define _Included_io_vproxy_msquic_QuicConnectionEventShutdownInitiatedByPeer
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventShutdownInitiatedByPeer;
typedef struct QuicConnectionEventShutdownInitiatedByPeer QuicConnectionEventShutdownInitiatedByPeer;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventShutdownInitiatedByPeer, QuicConnectionEventShutdownInitiatedByPeer *)

PNI_PACK(struct, QuicConnectionEventShutdownInitiatedByPeer, {
    int64_t ErrorCode;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventShutdownInitiatedByPeer
// metadata.generator-version: pni 21.0.0.8
// sha256:69fd960999dd23214756ceb17066664506c58491f75791f94ba5279c7fdd5556
