/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicBuffer */
#ifndef _Included_io_vproxy_msquic_QuicBuffer
#define _Included_io_vproxy_msquic_QuicBuffer
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_BUFFER, QUIC_BUFFER *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicBuffer
// metadata.generator-version: pni 21.0.0.8
// sha256:b4a6c495efd46266b41a20aec52c862f61a11f5db8b856a011d1451afbc38d3f
