/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicApiTable */
#ifndef _Included_io_vproxy_msquic_QuicApiTable
#define _Included_io_vproxy_msquic_QuicApiTable
#ifdef __cplusplus
extern "C" {
#endif

struct QuicApiTable;
typedef struct QuicApiTable QuicApiTable;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicRegistration.h"
#include "io_vproxy_msquic_QuicRegistrationConfig.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicApiTable, QuicApiTable *)

PNI_PACK(struct, QuicApiTable, {
    void * Api;
});

JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicApiTable_close(QuicApiTable * self);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicApiTable_setContext(QuicApiTable * self, void * Handle, void * Context);
JNIEXPORT void * JNICALL JavaCritical_io_vproxy_msquic_QuicApiTable_getContext(QuicApiTable * self, void * Handle);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicApiTable_setCallbackHandler(QuicApiTable * self, void * Handle, void * Handler, void * Context);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicApiTable_setParam(QuicApiTable * self, void * Handle, int32_t Param, int32_t BufferLength, void * Buffer);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicApiTable_getParam(QuicApiTable * self, void * Handle, int32_t Param, uint32_t * BufferLength, void * Buffer);
JNIEXPORT QuicRegistration * JNICALL JavaCritical_io_vproxy_msquic_QuicApiTable_openRegistration(QuicApiTable * self, QUIC_REGISTRATION_CONFIG * Config, int32_t * returnStatus, QuicRegistration * return_);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicApiTable
// metadata.generator-version: pni 21.0.0.8
// sha256:b54b937eff15689d1652c9ba3624b0526e5ea23d192d464283b6723e3d77d024
