/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEvent */
#ifndef _Included_io_vproxy_msquic_QuicStreamEvent
#define _Included_io_vproxy_msquic_QuicStreamEvent
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicStreamEventUnion.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_STREAM_EVENT, QUIC_STREAM_EVENT *)
PNIBufExpand(QUIC_STREAM_EVENT, QUIC_STREAM_EVENT, 40)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEvent
// metadata.generator-version: pni 21.0.0.12
// sha256:078d15ef419e1faaa8ad06c40739e62a54552b696232573c34af2e1da79349ef
