/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicRegistrationConfig */
#ifndef _Included_io_vproxy_msquic_QuicRegistrationConfig
#define _Included_io_vproxy_msquic_QuicRegistrationConfig
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_REGISTRATION_CONFIG, QUIC_REGISTRATION_CONFIG *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicRegistrationConfig
// metadata.generator-version: pni 21.0.0.8
// sha256:88e3bf329b2eef73925aafa5a09a49069dc8ee899c4b12f652f37e870c57b72e
