/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventIdealProcessorChanged */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventIdealProcessorChanged
#define _Included_io_vproxy_msquic_QuicConnectionEventIdealProcessorChanged
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventIdealProcessorChanged;
typedef struct QuicConnectionEventIdealProcessorChanged QuicConnectionEventIdealProcessorChanged;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventIdealProcessorChanged, QuicConnectionEventIdealProcessorChanged *)

PNI_PACK(struct, QuicConnectionEventIdealProcessorChanged, {
    uint16_t IdealProcessor;
    uint16_t PartitionIndex;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventIdealProcessorChanged
// metadata.generator-version: pni 21.0.0.8
// sha256:ec3e8c876915f65e53fa73a383c42373a2866cd3ccfe8dfc8c302c9ae21e3b5f
