/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicTLSSecret */
#ifndef _Included_io_vproxy_msquic_QuicTLSSecret
#define _Included_io_vproxy_msquic_QuicTLSSecret
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicTLSSecretIsSet.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_TLS_SECRETS, QUIC_TLS_SECRETS *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicTLSSecret
// metadata.generator-version: pni 21.0.0.8
// sha256:ca31837c759ae040f40f6cc47b1de6fe26b039598559cc6c68e5aa697a1267c8
