/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicTLSSecret */
#ifndef _Included_io_vproxy_msquic_QuicTLSSecret
#define _Included_io_vproxy_msquic_QuicTLSSecret
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicTLSSecretIsSet.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_TLS_SECRETS, QUIC_TLS_SECRETS *)
PNIBufExpand(QUIC_TLS_SECRETS, QUIC_TLS_SECRETS, 354)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicTLSSecret
// metadata.generator-version: pni 21.0.0.12
// sha256:1d1a4df7b9f974cea7be1c856bfd37247a72636c38a86759ac0b77e1e94048e7
