/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventIdealSendBufferSize */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventIdealSendBufferSize
#define _Included_io_vproxy_msquic_QuicStreamEventIdealSendBufferSize
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventIdealSendBufferSize;
typedef struct QuicStreamEventIdealSendBufferSize QuicStreamEventIdealSendBufferSize;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventIdealSendBufferSize, QuicStreamEventIdealSendBufferSize *)
PNIBufExpand(QuicStreamEventIdealSendBufferSize, QuicStreamEventIdealSendBufferSize, 8)

struct QuicStreamEventIdealSendBufferSize {
    uint64_t ByteCount;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventIdealSendBufferSize
// metadata.generator-version: pni 21.0.0.13
// sha256:5d0f9600bc3eafca269a9559327286d82378a21d9b23b39c905ed81a26536568
