/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventReliableResetNegotiated */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventReliableResetNegotiated
#define _Included_io_vproxy_msquic_QuicConnectionEventReliableResetNegotiated
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventReliableResetNegotiated;
typedef struct QuicConnectionEventReliableResetNegotiated QuicConnectionEventReliableResetNegotiated;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventReliableResetNegotiated, QuicConnectionEventReliableResetNegotiated *)
PNIBufExpand(QuicConnectionEventReliableResetNegotiated, QuicConnectionEventReliableResetNegotiated, 1)

struct QuicConnectionEventReliableResetNegotiated {
    uint8_t IsNegotiated;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventReliableResetNegotiated
// metadata.generator-version: pni 21.0.0.13
// sha256:14d7500f94caec3006198d83c8321d2ec6d465c45e64dd772893f2ddc5516b09
