/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicListenerEvent */
#ifndef _Included_io_vproxy_msquic_QuicListenerEvent
#define _Included_io_vproxy_msquic_QuicListenerEvent
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicListenerEventUnion.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_LISTENER_EVENT, QUIC_LISTENER_EVENT *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicListenerEvent
// metadata.generator-version: pni 21.0.0.8
// sha256:0917e15728dcc2bae3a521b1d611e7db725c7d2fa3d58e4bb65b0ce210e0fc94
