/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicAddr */
#ifndef _Included_io_vproxy_msquic_QuicAddr
#define _Included_io_vproxy_msquic_QuicAddr
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_ADDR, QUIC_ADDR *)

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_msquic_QuicAddr___getLayoutByteSize();

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_getFamily(QUIC_ADDR * self);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_setFamily(QUIC_ADDR * self, int32_t family);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_getPort(QUIC_ADDR * self);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_setPort(QUIC_ADDR * self, int32_t port);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_toString(QUIC_ADDR * self, char * str);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicAddr
// metadata.generator-version: pni 21.0.0.11
// sha256:ef6e436954c24c4e9e1b5a978c8e66f13814f1d7e4b356d3cbeb8602169ef62c
