/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicExecutionConfig */
#ifndef _Included_io_vproxy_msquic_QuicExecutionConfig
#define _Included_io_vproxy_msquic_QuicExecutionConfig
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_EXECUTION_CONFIG, QUIC_EXECUTION_CONFIG *)
PNIBufExpand(QUIC_EXECUTION_CONFIG, QUIC_EXECUTION_CONFIG, 16)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicExecutionConfig
// metadata.generator-version: pni 21.0.0.17
// sha256:97ce0946cbb61e4b361dee8da3167abec310bf782c2c82d4d488a9383902af94
