/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventReliableResetNegotiated */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventReliableResetNegotiated
#define _Included_io_vproxy_msquic_QuicConnectionEventReliableResetNegotiated
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventReliableResetNegotiated;
typedef struct QuicConnectionEventReliableResetNegotiated QuicConnectionEventReliableResetNegotiated;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventReliableResetNegotiated, QuicConnectionEventReliableResetNegotiated *)

PNI_PACK(struct, QuicConnectionEventReliableResetNegotiated, {
    uint8_t IsNegotiated;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventReliableResetNegotiated
// metadata.generator-version: pni 21.0.0.8
// sha256:f79a8a3317036425993674fa1a8306ca330351f3778ca984e977e8daca825b7b
