/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicNewConnectionInfo */
#ifndef _Included_io_vproxy_msquic_QuicNewConnectionInfo
#define _Included_io_vproxy_msquic_QuicNewConnectionInfo
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicAddr.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_NEW_CONNECTION_INFO, QUIC_NEW_CONNECTION_INFO *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicNewConnectionInfo
// metadata.generator-version: pni 21.0.0.8
// sha256:f29f5ba756455e6a2cb62242c8dbd7dccddb10a5334066f60026fc13ce0d71d3
