/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEvent */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEvent
#define _Included_io_vproxy_msquic_QuicConnectionEvent
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicConnectionEventUnion.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_CONNECTION_EVENT, QUIC_CONNECTION_EVENT *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEvent
// metadata.generator-version: pni 21.0.0.8
// sha256:99bd778a2b752fb6db3d79695a6a7cae9556e0290c0f8101d50c7ce95e84e670
