/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventStreamsAvailable */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventStreamsAvailable
#define _Included_io_vproxy_msquic_QuicConnectionEventStreamsAvailable
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventStreamsAvailable;
typedef struct QuicConnectionEventStreamsAvailable QuicConnectionEventStreamsAvailable;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventStreamsAvailable, QuicConnectionEventStreamsAvailable *)

PNI_PACK(struct, QuicConnectionEventStreamsAvailable, {
    uint16_t BidirectionalCount;
    uint16_t UnidirectionalCount;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventStreamsAvailable
// metadata.generator-version: pni 21.0.0.8
// sha256:730663264beec575b998b94e0b25cda612014e26cf3998160dce10dbd14179f8
