/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicSettings */
#ifndef _Included_io_vproxy_msquic_QuicSettings
#define _Included_io_vproxy_msquic_QuicSettings
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicSettingsIsSet.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_SETTINGS, QUIC_SETTINGS *)
PNIBufExpand(QUIC_SETTINGS, QUIC_SETTINGS, 128)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicSettings
// metadata.generator-version: pni 21.0.0.12
// sha256:0ec0c1f6d1893ff65e5668d3e891872f5dc2b0e59a4276c0c7b4344280275762
