/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicSettings */
#ifndef _Included_io_vproxy_msquic_QuicSettings
#define _Included_io_vproxy_msquic_QuicSettings
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicSettingsIsSet.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_SETTINGS, QUIC_SETTINGS *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicSettings
// metadata.generator-version: pni 21.0.0.8
// sha256:fe88a3edec3254070e16e3783f9ed8941dde2b9002bf3996e01d005d6d25051f
