/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventStartComplete */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventStartComplete
#define _Included_io_vproxy_msquic_QuicStreamEventStartComplete
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventStartComplete;
typedef struct QuicStreamEventStartComplete QuicStreamEventStartComplete;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventStartComplete, QuicStreamEventStartComplete *)

PNI_PACK(struct, QuicStreamEventStartComplete, {
    int32_t Status; /* padding */ uint64_t :32;
    int64_t ID;
    uint8_t PeerAccepted : 1;
    uint8_t : 7;
     /* padding */ uint64_t :56;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventStartComplete
// metadata.generator-version: pni 21.0.0.8
// sha256:0520ffb4054276db54573767f4d9d2ca5997775471ce68cc1c1607368501df21
