/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventUnion */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventUnion
#define _Included_io_vproxy_msquic_QuicStreamEventUnion
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicStreamEventStartComplete.h"
#include "io_vproxy_msquic_QuicStreamEventReceive.h"
#include "io_vproxy_msquic_QuicStreamEventSendComplete.h"
#include "io_vproxy_msquic_QuicStreamEventPeerSendAborted.h"
#include "io_vproxy_msquic_QuicStreamEventPeerReceiveAborted.h"
#include "io_vproxy_msquic_QuicStreamEventSendShutdownComplete.h"
#include "io_vproxy_msquic_QuicStreamEventShutdownComplete.h"
#include "io_vproxy_msquic_QuicStreamEventIdealSendBufferSize.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventUnion
// metadata.generator-version: pni 21.0.0.8
// sha256:d45d86ad3ae3b5ecff1a94703efbf23885df722346a859e70e6df6f5c2b835a4
