/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventPeerReceiveAborted */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventPeerReceiveAborted
#define _Included_io_vproxy_msquic_QuicStreamEventPeerReceiveAborted
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventPeerReceiveAborted;
typedef struct QuicStreamEventPeerReceiveAborted QuicStreamEventPeerReceiveAborted;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventPeerReceiveAborted, QuicStreamEventPeerReceiveAborted *)

PNI_PACK(struct, QuicStreamEventPeerReceiveAborted, {
    int64_t ErrorCode;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventPeerReceiveAborted
// metadata.generator-version: pni 21.0.0.8
// sha256:e1d7e64c4152fe1744e65b88ebdce9aacbae99c2e99948d6f95cbb915c678cdd
