/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicCredentialConfig */
#ifndef _Included_io_vproxy_msquic_QuicCredentialConfig
#define _Included_io_vproxy_msquic_QuicCredentialConfig
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicCertificate.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_CREDENTIAL_CONFIG, QUIC_CREDENTIAL_CONFIG *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicCredentialConfig
// metadata.generator-version: pni 21.0.0.8
// sha256:4f9cd1336b0e6c579ec72a5cbf3f65a85f1335a97c75e835ef0737c5690dc519
