/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicNewConnectionInfo */
#ifndef _Included_io_vproxy_msquic_QuicNewConnectionInfo
#define _Included_io_vproxy_msquic_QuicNewConnectionInfo
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicAddr.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_NEW_CONNECTION_INFO, QUIC_NEW_CONNECTION_INFO *)
PNIBufExpand(QUIC_NEW_CONNECTION_INFO, QUIC_NEW_CONNECTION_INFO, 72)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicNewConnectionInfo
// metadata.generator-version: pni 21.0.0.12
// sha256:65d753a667cd7d1238701fe92acb2507869b27b422a30ae6b7124bfe3fbb6c82
