/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConfiguration */
#ifndef _Included_io_vproxy_msquic_QuicConfiguration
#define _Included_io_vproxy_msquic_QuicConfiguration
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConfiguration;
typedef struct QuicConfiguration QuicConfiguration;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicObjectBase.h"
#include "io_vproxy_msquic_QuicCredentialConfig.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConfiguration, QuicConfiguration *)
PNIBufExpand(QuicConfiguration, QuicConfiguration, 16)

struct QuicConfiguration {
    QuicObjectBase SUPER;
};

JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicConfiguration_close(QuicConfiguration * self);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicConfiguration_loadCredential(QuicConfiguration * self, QUIC_CREDENTIAL_CONFIG * CredConfig);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConfiguration
// metadata.generator-version: pni 21.0.0.17
// sha256:5eba8cf201afbeb2e49bd40e44a7a0618fd711cdecfdbf5c85246d820815660b
