/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEvent */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEvent
#define _Included_io_vproxy_msquic_QuicConnectionEvent
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicConnectionEventUnion.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_CONNECTION_EVENT, QUIC_CONNECTION_EVENT *)
PNIBufExpand(QUIC_CONNECTION_EVENT, QUIC_CONNECTION_EVENT, 32)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEvent
// metadata.generator-version: pni 21.0.0.12
// sha256:2de6a82bf6cbd34e5ab395ba7e399cd9c239e9fafab58ce2167592e6fd80f067
