/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventConnected */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventConnected
#define _Included_io_vproxy_msquic_QuicConnectionEventConnected
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventConnected;
typedef struct QuicConnectionEventConnected QuicConnectionEventConnected;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventConnected, QuicConnectionEventConnected *)
PNIBufExpand(QuicConnectionEventConnected, QuicConnectionEventConnected, 16)

struct QuicConnectionEventConnected {
    uint8_t SessionResumed;
    uint8_t NegotiatedAlpnLength;
    void * NegotiatedAlpn;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventConnected
// metadata.generator-version: pni 21.0.0.13
// sha256:3ace30ff4a8a396e6e986f161b83e56b13d31c542ea0194e0113e704b08197e7
