/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicListenerEvent */
#ifndef _Included_io_vproxy_msquic_QuicListenerEvent
#define _Included_io_vproxy_msquic_QuicListenerEvent
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicListenerEventUnion.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_LISTENER_EVENT, QUIC_LISTENER_EVENT *)
PNIBufExpand(QUIC_LISTENER_EVENT, QUIC_LISTENER_EVENT, 24)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicListenerEvent
// metadata.generator-version: pni 21.0.0.12
// sha256:4f60c5c9b1a88368af12610ce938aa5ea477251bf8d0b493b711e6828ca7468c
