/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventUnion */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventUnion
#define _Included_io_vproxy_msquic_QuicConnectionEventUnion
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicConnectionEventConnected.h"
#include "io_vproxy_msquic_QuicConnectionEventShutdownInitiatedByTransport.h"
#include "io_vproxy_msquic_QuicConnectionEventShutdownInitiatedByPeer.h"
#include "io_vproxy_msquic_QuicConnectionEventConnectionShutdownComplete.h"
#include "io_vproxy_msquic_QuicConnectionEventLocalAddressChanged.h"
#include "io_vproxy_msquic_QuicConnectionEventPeerAddressChanged.h"
#include "io_vproxy_msquic_QuicConnectionEventPeerStreamStarted.h"
#include "io_vproxy_msquic_QuicConnectionEventStreamsAvailable.h"
#include "io_vproxy_msquic_QuicConnectionEventPeerNeedsStreams.h"
#include "io_vproxy_msquic_QuicConnectionEventIdealProcessorChanged.h"
#include "io_vproxy_msquic_QuicConnectionEventDatagramStateChanged.h"
#include "io_vproxy_msquic_QuicConnectionEventDatagramReceived.h"
#include "io_vproxy_msquic_QuicConnectionEventDatagramSendStateChanged.h"
#include "io_vproxy_msquic_QuicConnectionEventResumed.h"
#include "io_vproxy_msquic_QuicConnectionEventResumptionTicketReceived.h"
#include "io_vproxy_msquic_QuicConnectionEventPeerCertificateReceived.h"
#include "io_vproxy_msquic_QuicConnectionEventReliableResetNegotiated.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventUnion
// metadata.generator-version: pni 21.0.0.8
// sha256:8fa9d70ab067d56b89affc3ed5c8c0e9f16b4056130a57ff1d6298c1258fa687
