/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_MsQuicValues */
#ifndef _Included_io_vproxy_msquic_MsQuicValues
#define _Included_io_vproxy_msquic_MsQuicValues
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT char * JNICALL JavaCritical_io_vproxy_msquic_MsQuicValues_QuicStatusString(int32_t status);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicValues_sizeofQuicAddr(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicValues_QUIC_STATUS_NOT_SUPPORTED(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicValues_QUIC_STATUS_PENDING(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicValues_QUIC_ADDRESS_FAMILY_UNSPEC(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicValues_QUIC_ADDRESS_FAMILY_INET(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicValues_QUIC_ADDRESS_FAMILY_INET6(void);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_MsQuicValues
// metadata.generator-version: pni 21.0.0.8
// sha256:0667a9ee92e531facfdc7a462cc6ff773266d8c84a8aee33b1eba5e76f8d6566
