/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_MsQuic */
#ifndef _Included_io_vproxy_msquic_MsQuic
#define _Included_io_vproxy_msquic_MsQuic
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicApiTable.h"
#include "io_vproxy_msquic_QuicAddr.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT QuicApiTable * JNICALL JavaCritical_io_vproxy_msquic_MsQuic_open(uint32_t Version, int32_t * returnStatus, QuicApiTable * return_);
JNIEXPORT uint8_t JNICALL JavaCritical_io_vproxy_msquic_MsQuic_buildQuicAddr(char * addr, int32_t port, QUIC_ADDR * result);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_MsQuic
// metadata.generator-version: pni 21.0.0.8
// sha256:814d69084ae8cfab8a5e36dfedae0d886a9a607513de70e767b7fa13e8a3ba88
