/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventResumed */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventResumed
#define _Included_io_vproxy_msquic_QuicConnectionEventResumed
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventResumed;
typedef struct QuicConnectionEventResumed QuicConnectionEventResumed;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventResumed, QuicConnectionEventResumed *)

PNI_PACK(struct, QuicConnectionEventResumed, {
    uint16_t ResumptionStateLength; /* padding */ uint64_t :48;
    void * ResumptionState;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventResumed
// metadata.generator-version: pni 21.0.0.8
// sha256:c8f5ff18bfc100bbfd736938fddb1438690de58d84f989a30d6c52d3238a8879
