/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicAddr */
#ifndef _Included_io_vproxy_msquic_QuicAddr
#define _Included_io_vproxy_msquic_QuicAddr
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_ADDR, QUIC_ADDR *)

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_getFamily(QUIC_ADDR * self);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_setFamily(QUIC_ADDR * self, int32_t family);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_getPort(QUIC_ADDR * self);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_setPort(QUIC_ADDR * self, int32_t port);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicAddr_toString(QUIC_ADDR * self, char * str);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicAddr
// metadata.generator-version: pni 21.0.0.8
// sha256:d9b4e99053ba526b9e899c9a9697682054eeabba8281a4502add2c6799855ea8
