/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventShutdownInitiatedByPeer */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventShutdownInitiatedByPeer
#define _Included_io_vproxy_msquic_QuicConnectionEventShutdownInitiatedByPeer
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventShutdownInitiatedByPeer;
typedef struct QuicConnectionEventShutdownInitiatedByPeer QuicConnectionEventShutdownInitiatedByPeer;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventShutdownInitiatedByPeer, QuicConnectionEventShutdownInitiatedByPeer *)
PNIBufExpand(QuicConnectionEventShutdownInitiatedByPeer, QuicConnectionEventShutdownInitiatedByPeer, 8)

struct QuicConnectionEventShutdownInitiatedByPeer {
    int64_t ErrorCode;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventShutdownInitiatedByPeer
// metadata.generator-version: pni 21.0.0.13
// sha256:f1ba149f445caa3d10d8137a9bb674a9af3b45b2cf233bb06aba03876cd1ba57
