/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventShutdownComplete */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventShutdownComplete
#define _Included_io_vproxy_msquic_QuicStreamEventShutdownComplete
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventShutdownComplete;
typedef struct QuicStreamEventShutdownComplete QuicStreamEventShutdownComplete;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventShutdownComplete, QuicStreamEventShutdownComplete *)
PNIBufExpand(QuicStreamEventShutdownComplete, QuicStreamEventShutdownComplete, 24)

struct QuicStreamEventShutdownComplete {
    uint8_t ConnectionShutdown;
    uint8_t AppCloseInProgress : 1;
    uint8_t ConnectionShutdownByApp : 1;
    uint8_t ConnectionClosedRemotely : 1;
    uint8_t : 5;

    int64_t ConnectionErrorCode;
    int32_t ConnectionCloseStatus;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventShutdownComplete
// metadata.generator-version: pni 21.0.0.13
// sha256:2b5e9b6e869c3af51c69d86b926203e6bb932e3bd52de7885106933f05f16b84
