/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventDatagramReceived */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventDatagramReceived
#define _Included_io_vproxy_msquic_QuicConnectionEventDatagramReceived
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventDatagramReceived;
typedef struct QuicConnectionEventDatagramReceived QuicConnectionEventDatagramReceived;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicBuffer.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventDatagramReceived, QuicConnectionEventDatagramReceived *)

PNI_PACK(struct, QuicConnectionEventDatagramReceived, {
    QUIC_BUFFER Buffer;
    int32_t Flags; /* padding */ uint64_t :32;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventDatagramReceived
// metadata.generator-version: pni 21.0.0.8
// sha256:34dd0b9cbdc2d5ef41d2ef162e5751b4a8c2804b17446a6fea8fafc0fe1aa6e3
