/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_MsQuicMod */
#ifndef _Included_io_vproxy_msquic_MsQuicMod
#define _Included_io_vproxy_msquic_MsQuicMod
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicExtraApiTable.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT QUIC_EXTRA_API_TABLE * JNICALL JavaCritical_io_vproxy_msquic_MsQuicMod_openExtra(uint32_t Version, int32_t * returnStatus);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_MsQuicMod_INVOKE_LPTHREAD_START_ROUTINE(void * Callback, void * Context);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_MsQuicMod
// metadata.generator-version: pni 21.0.0.17
// sha256:e116836c8b505ad085baca0e775e3ee3301a9fec4f9e6ee311dbd9c76cca1258
