/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventSendShutdownComplete */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventSendShutdownComplete
#define _Included_io_vproxy_msquic_QuicStreamEventSendShutdownComplete
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventSendShutdownComplete;
typedef struct QuicStreamEventSendShutdownComplete QuicStreamEventSendShutdownComplete;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventSendShutdownComplete, QuicStreamEventSendShutdownComplete *)

PNI_PACK(struct, QuicStreamEventSendShutdownComplete, {
    uint8_t Graceful;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventSendShutdownComplete
// metadata.generator-version: pni 21.0.0.8
// sha256:5c0af27ea8db734f74ebf2f5092eb2e6051c4834d3f1b7359cc41987ee932eb8
