/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventIdealSendBufferSize */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventIdealSendBufferSize
#define _Included_io_vproxy_msquic_QuicStreamEventIdealSendBufferSize
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventIdealSendBufferSize;
typedef struct QuicStreamEventIdealSendBufferSize QuicStreamEventIdealSendBufferSize;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventIdealSendBufferSize, QuicStreamEventIdealSendBufferSize *)

PNI_PACK(struct, QuicStreamEventIdealSendBufferSize, {
    uint64_t ByteCount;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventIdealSendBufferSize
// metadata.generator-version: pni 21.0.0.8
// sha256:88cecd6cc5887f485e69716843ecb9674a64f7648ec0e858e7839a6888323536
