/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicCertificateFile */
#ifndef _Included_io_vproxy_msquic_QuicCertificateFile
#define _Included_io_vproxy_msquic_QuicCertificateFile
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QUIC_CERTIFICATE_FILE, QUIC_CERTIFICATE_FILE *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicCertificateFile
// metadata.generator-version: pni 21.0.0.8
// sha256:7ca97a099e77d7b60ab1c4f4832dda4c9a2185304e5810e5820b1acde28e3975
