/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventSendShutdownComplete */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventSendShutdownComplete
#define _Included_io_vproxy_msquic_QuicStreamEventSendShutdownComplete
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventSendShutdownComplete;
typedef struct QuicStreamEventSendShutdownComplete QuicStreamEventSendShutdownComplete;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventSendShutdownComplete, QuicStreamEventSendShutdownComplete *)
PNIBufExpand(QuicStreamEventSendShutdownComplete, QuicStreamEventSendShutdownComplete, 1)

struct QuicStreamEventSendShutdownComplete {
    uint8_t Graceful;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventSendShutdownComplete
// metadata.generator-version: pni 21.0.0.13
// sha256:98c7e012d783050d4a714e7d0d86f7fc49d2fdfff57fe44d89d65c9d4c0de637
