/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventDatagramSendStateChanged */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventDatagramSendStateChanged
#define _Included_io_vproxy_msquic_QuicConnectionEventDatagramSendStateChanged
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventDatagramSendStateChanged;
typedef struct QuicConnectionEventDatagramSendStateChanged QuicConnectionEventDatagramSendStateChanged;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventDatagramSendStateChanged, QuicConnectionEventDatagramSendStateChanged *)

PNI_PACK(struct, QuicConnectionEventDatagramSendStateChanged, {
    void * ClientContext;
    int32_t State; /* padding */ uint64_t :32;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventDatagramSendStateChanged
// metadata.generator-version: pni 21.0.0.8
// sha256:93250d0a92fbab36abaf66c05935dd3e06dd44fab929e5c7a48c15f301004b21
