/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnection */
#ifndef _Included_io_vproxy_msquic_QuicConnection
#define _Included_io_vproxy_msquic_QuicConnection
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnection;
typedef struct QuicConnection QuicConnection;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicObjectBase.h"
#include "io_vproxy_msquic_QuicConfiguration.h"
#include "io_vproxy_msquic_QuicStream.h"
#include "io_vproxy_msquic_QuicBuffer.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnection, QuicConnection *)
PNIBufExpand(QuicConnection, QuicConnection, 16)

struct QuicConnection {
    QuicObjectBase SUPER;
};

JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicConnection_close(QuicConnection * self);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_QuicConnection_shutdown(QuicConnection * self, int32_t Flags, int64_t ErrorCode);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicConnection_start(QuicConnection * self, QuicConfiguration * Conf, int32_t Family, char * ServerName, int32_t ServerPort);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicConnection_setConfiguration(QuicConnection * self, QuicConfiguration * Conf);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicConnection_sendResumptionTicket(QuicConnection * self, int32_t Flags, int32_t DataLength, void * ResumptionData);
JNIEXPORT QuicStream * JNICALL JavaCritical_io_vproxy_msquic_QuicConnection_openStream(QuicConnection * self, int32_t Flags, void * Handler, void * Context, int32_t * returnStatus, QuicStream * return_);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicConnection_sendDatagram(QuicConnection * self, QUIC_BUFFER * Buffers, int32_t BufferCount, int32_t Flags, void * ClientSendContext);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicConnection_resumptionTicketValidationComplete(QuicConnection * self, uint8_t Result);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_QuicConnection_certificateValidationComplete(QuicConnection * self, uint8_t Result, int32_t TlsAlert);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnection
// metadata.generator-version: pni 21.0.0.17
// sha256:428a2ddafd363bafbc0e52e9426184201a007c6573e7acbb9627352a0b51bf27
