/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventStartComplete */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventStartComplete
#define _Included_io_vproxy_msquic_QuicStreamEventStartComplete
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventStartComplete;
typedef struct QuicStreamEventStartComplete QuicStreamEventStartComplete;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventStartComplete, QuicStreamEventStartComplete *)
PNIBufExpand(QuicStreamEventStartComplete, QuicStreamEventStartComplete, 24)

struct QuicStreamEventStartComplete {
    int32_t Status;
    int64_t ID;
    uint8_t PeerAccepted : 1;
    uint8_t : 7;

};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventStartComplete
// metadata.generator-version: pni 21.0.0.13
// sha256:5a919550da4428f5c6558010e63912e2812066985017445c966cf0687fc774ae
