/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventDatagramStateChanged */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventDatagramStateChanged
#define _Included_io_vproxy_msquic_QuicConnectionEventDatagramStateChanged
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventDatagramStateChanged;
typedef struct QuicConnectionEventDatagramStateChanged QuicConnectionEventDatagramStateChanged;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventDatagramStateChanged, QuicConnectionEventDatagramStateChanged *)

PNI_PACK(struct, QuicConnectionEventDatagramStateChanged, {
    uint8_t SendEnabled; /* padding */ uint64_t :8;
    uint16_t MaxSendLength;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventDatagramStateChanged
// metadata.generator-version: pni 21.0.0.8
// sha256:f75d37c8b8acf41cc982acb5afea4d8e1b431bbc67e9e81d05e0f7d10ba4fd23
