/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicStreamEventPeerSendAborted */
#ifndef _Included_io_vproxy_msquic_QuicStreamEventPeerSendAborted
#define _Included_io_vproxy_msquic_QuicStreamEventPeerSendAborted
#ifdef __cplusplus
extern "C" {
#endif

struct QuicStreamEventPeerSendAborted;
typedef struct QuicStreamEventPeerSendAborted QuicStreamEventPeerSendAborted;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicStreamEventPeerSendAborted, QuicStreamEventPeerSendAborted *)

PNI_PACK(struct, QuicStreamEventPeerSendAborted, {
    int64_t ErrorCode;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicStreamEventPeerSendAborted
// metadata.generator-version: pni 21.0.0.8
// sha256:409da8a82e245f6496c4433f9dfa24feb26c212e3698e29778b5971ee03624aa
