/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicConnectionEventLocalAddressChanged */
#ifndef _Included_io_vproxy_msquic_QuicConnectionEventLocalAddressChanged
#define _Included_io_vproxy_msquic_QuicConnectionEventLocalAddressChanged
#ifdef __cplusplus
extern "C" {
#endif

struct QuicConnectionEventLocalAddressChanged;
typedef struct QuicConnectionEventLocalAddressChanged QuicConnectionEventLocalAddressChanged;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicAddr.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicConnectionEventLocalAddressChanged, QuicConnectionEventLocalAddressChanged *)

PNI_PACK(struct, QuicConnectionEventLocalAddressChanged, {
    QUIC_ADDR * Address;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicConnectionEventLocalAddressChanged
// metadata.generator-version: pni 21.0.0.8
// sha256:d8a1fc9abaccab515d2250ce14d3f67aa0d173b5afce6d7fc7fb02dc87de918e
