/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class msquic_internal_NativeValues */

#ifndef _Included_msquic_internal_NativeValues
#define _Included_msquic_internal_NativeValues
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_ADDRESS_FAMILY_UNSPEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1ADDRESS_1FAMILY_1UNSPEC
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_ADDRESS_FAMILY_INET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1ADDRESS_1FAMILY_1INET
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_ADDRESS_FAMILY_INET6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1ADDRESS_1FAMILY_1INET6
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_CONNECTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1CONNECTED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_SHUTDOWN_INITIATED_BY_TRANSPORT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1SHUTDOWN_1INITIATED_1BY_1TRANSPORT
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_SHUTDOWN_INITIATED_BY_PEER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1SHUTDOWN_1INITIATED_1BY_1PEER
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_SHUTDOWN_COMPLETE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1SHUTDOWN_1COMPLETE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_LOCAL_ADDRESS_CHANGED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1LOCAL_1ADDRESS_1CHANGED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_PEER_ADDRESS_CHANGED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1PEER_1ADDRESS_1CHANGED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_PEER_STREAM_STARTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1PEER_1STREAM_1STARTED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_STREAMS_AVAILABLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1STREAMS_1AVAILABLE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_PEER_NEEDS_STREAMS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1PEER_1NEEDS_1STREAMS
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_IDEAL_PROCESSOR_CHANGED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1IDEAL_1PROCESSOR_1CHANGED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_DATAGRAM_STATE_CHANGED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1DATAGRAM_1STATE_1CHANGED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_DATAGRAM_RECEIVED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1DATAGRAM_1RECEIVED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_DATAGRAM_SEND_STATE_CHANGED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1DATAGRAM_1SEND_1STATE_1CHANGED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_RESUMED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1RESUMED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_EVENT_RESUMPTION_TICKET_RECEIVED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1EVENT_1RESUMPTION_1TICKET_1RECEIVED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_EXECUTION_PROFILE_LOW_LATENCY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1EXECUTION_1PROFILE_1LOW_1LATENCY
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_EXECUTION_PROFILE_TYPE_MAX_THROUGHPUT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1EXECUTION_1PROFILE_1TYPE_1MAX_1THROUGHPUT
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_EXECUTION_PROFILE_TYPE_SCAVENGER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1EXECUTION_1PROFILE_1TYPE_1SCAVENGER
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_EXECUTION_PROFILE_TYPE_REAL_TIME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1EXECUTION_1PROFILE_1TYPE_1REAL_1TIME
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_LISTENER_EVENT_NEW_CONNECTION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1LISTENER_1EVENT_1NEW_1CONNECTION
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_SEND_FLAG_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1SEND_1FLAG_1NONE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_SEND_FLAG_ALLOW_0_RTT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1SEND_1FLAG_1ALLOW_10_1RTT
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_SEND_FLAG_START
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1SEND_1FLAG_1START
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_SEND_FLAG_FIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1SEND_1FLAG_1FIN
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_SEND_FLAG_DGRAM_PRIORITY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1SEND_1FLAG_1DGRAM_1PRIORITY
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_SEND_RESUMPTION_FLAG_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1SEND_1RESUMPTION_1FLAG_1NONE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_SEND_RESUMPTION_FLAG_FINAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1SEND_1RESUMPTION_1FLAG_1FINAL
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_SERVER_NO_RESUME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1SERVER_1NO_1RESUME
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_SERVER_RESUME_ONLY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1SERVER_1RESUME_1ONLY
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_SERVER_RESUME_AND_ZERORTT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1SERVER_1RESUME_1AND_1ZERORTT
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_EVENT_START_COMPLETE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1EVENT_1START_1COMPLETE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_EVENT_RECEIVE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1EVENT_1RECEIVE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_EVENT_SEND_COMPLETE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1EVENT_1SEND_1COMPLETE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_EVENT_PEER_SEND_SHUTDOWN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1EVENT_1PEER_1SEND_1SHUTDOWN
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_EVENT_PEER_SEND_ABORTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1EVENT_1PEER_1SEND_1ABORTED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_EVENT_PEER_RECEIVE_ABORTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1EVENT_1PEER_1RECEIVE_1ABORTED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_EVENT_SEND_SHUTDOWN_COMPLETE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1EVENT_1SEND_1SHUTDOWN_1COMPLETE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_EVENT_SHUTDOWN_COMPLETE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1EVENT_1SHUTDOWN_1COMPLETE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_EVENT_IDEAL_SEND_BUFFER_SIZE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1EVENT_1IDEAL_1SEND_1BUFFER_1SIZE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_SHUTDOWN_FLAG_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1SHUTDOWN_1FLAG_1NONE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_SHUTDOWN_FLAG_GRACEFUL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1SHUTDOWN_1FLAG_1GRACEFUL
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_SHUTDOWN_FLAG_ABORT_SEND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1SHUTDOWN_1FLAG_1ABORT_1SEND
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_SHUTDOWN_FLAG_ABORT_RECEIVE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1SHUTDOWN_1FLAG_1ABORT_1RECEIVE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_SHUTDOWN_FLAG_ABORT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1SHUTDOWN_1FLAG_1ABORT
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_SHUTDOWN_FLAG_IMMEDIATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1SHUTDOWN_1FLAG_1IMMEDIATE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_ABORTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1ABORTED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_ADDRESS_IN_USE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1ADDRESS_1IN_1USE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_ALPN_NEG_FAILURE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1ALPN_1NEG_1FAILURE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_BUFFER_TOO_SMALL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1BUFFER_1TOO_1SMALL
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_CONNECTION_IDLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1CONNECTION_1IDLE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_CONNECTION_REFUSED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1CONNECTION_1REFUSED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_CONNECTION_TIMEOUT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1CONNECTION_1TIMEOUT
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_CONTINUE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1CONTINUE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_DNS_RESOLUTION_ERROR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1DNS_1RESOLUTION_1ERROR
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_EPOLL_ERROR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1EPOLL_1ERROR
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_HANDSHAKE_FAILURE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1HANDSHAKE_1FAILURE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_INTERNAL_ERROR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1INTERNAL_1ERROR
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_INVALID_PARAMETER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1INVALID_1PARAMETER
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_INVALID_STATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1INVALID_1STATE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_NOT_FOUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1NOT_1FOUND
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_NOT_SUPPORTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1NOT_1SUPPORTED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_OUT_OF_MEMORY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1OUT_1OF_1MEMORY
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_PENDING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1PENDING
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_PERMISSION_DENIED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1PERMISSION_1DENIED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_PROTOCOL_ERROR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1PROTOCOL_1ERROR
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_SOCKET_ERROR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1SOCKET_1ERROR
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_SUCCESS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1SUCCESS
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_TLS_ERROR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1TLS_1ERROR
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_UNREACHABLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1UNREACHABLE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_USER_CANCELED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1USER_1CANCELED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STATUS_VER_NEG_ERROR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STATUS_1VER_1NEG_1ERROR
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_OPEN_FLAG_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1OPEN_1FLAG_1NONE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_OPEN_FLAG_UNIDIRECTIONAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1OPEN_1FLAG_1UNIDIRECTIONAL
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_OPEN_FLAG_0_RTT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1OPEN_1FLAG_10_1RTT
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_START_FLAG_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1START_1FLAG_1NONE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_START_FLAG_FAIL_BLOCKED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1START_1FLAG_1FAIL_1BLOCKED
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_START_FLAG_IMMEDIATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1START_1FLAG_1IMMEDIATE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_STREAM_START_FLAG_ASYNC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1STREAM_1START_1FLAG_1ASYNC
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_RECEIVE_FLAG_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1RECEIVE_1FLAG_1NONE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_RECEIVE_FLAG_0_RTT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1RECEIVE_1FLAG_10_1RTT
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_RECEIVE_FLAG_FIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1RECEIVE_1FLAG_1FIN
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_SHUTDOWN_FLAG_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1SHUTDOWN_1FLAG_1NONE
  (JNIEnv *, jobject);

/*
 * Class:     msquic_internal_NativeValues
 * Method:    QUIC_CONNECTION_SHUTDOWN_FLAG_SILENT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_msquic_internal_NativeValues_QUIC_1CONNECTION_1SHUTDOWN_1FLAG_1SILENT
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
